#!/bin/sh

git submodule update --init --recursive
cd ./ext/tocha/
mkdir _build
cd _build
cmake ..
make
cd ../../../
python3 -m venv env
. env/bin/activate
pip install -r requirements.txt
mkdir _build
cd _build
cmake ..