#pragma once

namespace ops
{
    class AdamUpdate;
    class ArgmaxAccuracy;
    class Conv2D;
    class Conv2DBiasAdd;
    class Conv2DInputGrad;
    class Conv2DKernelGrad;
    class Conv2DBiasAddGrad;
    class Conv2DTranspose;
    class Conv2DTransposeInputGrad;
    class Conv2DTransposeKernelGrad;
    class CompiledOp;
    class Graph;
    class Input;
    class LeakyReluGrad;
    class LogSoftmax;
    class MatMatMul;
    class MatMulAdd;
    class MatRvectAdd;
    class MatSum;
    class MomentUpdate;
    class MSE;
    class MSEGrad;
    class Op;
    class OpsBuilder;
    class ReluGrad;
    class Shape;
    class Seq;
    class SigmoidCrossEntropy;
    class SigmoidCrossEntropyGrad;
    class SigmoidGrad;
    class Softmax;
    class SoftmaxCrossEntropy;
    class SoftmaxCrossEntropyGrad;
    class TanhGrad;
    class Update;
    class Variable;
    class VectSigmoid;
    class VectRelu;
    class VectReluLeaky;
    class VectTanh;
    class Reshape;
}
